[Settings]
# X, Y coordinates for pdir
location1 = 400,800
# X, Y coordinates for conda
location2 = 600,500
# Prefix for pdir's image
prefix1 = 02_
# Prefix for conda's image
prefix2 = 06_
# Font scale for cv2.putText
font_scale = 2
# Thickness of the text font
font_thickness = 3
# Color of the text
font_color = 0,255,0